services:
  - type: web
    name: medigo-platform
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RAZORPAY_key_id
        sync: false
      - key: RAZORPAY_live_key_secret
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
